name: "Release Collector Lambda layer"

on:
  # (Using tag push instead of release to allow filtering by tag prefix.)
  push:
    tags:
      - layer-collector/**

permissions:
  id-token: write
  contents: read

jobs:
  build-layer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    outputs:
      COLLECTOR_VERSION: ${{ steps.save-collector-version.outputs.COLLECTOR_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
      - name: build
        run: make -C collector package GOARCH=${{ matrix.architecture }}
      - uses: actions/upload-artifact@v3
        with:
          name: collector-extension-${{ matrix.architecture }}.zip
          path: ${{ github.workspace }}/collector/build/*.zip

      - name: Save Collector Version
        if: ${{ matrix.architecture == 'amd64' }}
        id: save-collector-version
        shell: bash
        run: echo COLLECTOR_VERSION=$(collector/build/extensions/collector -v | head -n 1 | jq -r .version) >> "$GITHUB_OUTPUT"

  publish-layer:
    uses: ./.github/workflows/layer-publish.yml
    needs: build-layer
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        aws_region:
         - eu-west-2
         - us-east-1
    with:
      artifact-name: collector-extension-${{ matrix.architecture }}.zip
      layer-name: opentelemetry-collector
      component-version: ${{needs.build-layer.outputs.COLLECTOR_VERSION}}
      architecture: ${{ matrix.architecture }}
      aws_region: ${{ matrix.aws_region }}
    secrets: inherit
